// Prompt 1: The Fibonacci Sequence... Each new term in the Fibonacci sequence is generated by adding the previous two numbers together. By starting with 1 and 2, the first 10 numbers will be:0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose maximum value does not exceed four million, find the sum of the even-valued terms.

// let numb = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

let fib = [0,1];
let temp = 0;

for (let i = 2; i < 100; i++) {
    fib[i] = fib[i -2] + fib[i - 1]
    if (fib[i] % 2 === 0) {
        temp += fib[i]
    }
}

console.log(temp)
